# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Infrastructure

## Application framework
gem 'rails', '~> 6.0'
## Postgresql for Database
gem 'pg', '>= 0.18', '< 2.0'
## Puma for concurrent request handling
gem 'puma', '~> 4.3'

# Internationalization and Regionalization

## Windows does not include zoneinfo files, so bundle the
## tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Finance
## Handles rounding errors and provides a type system
gem 'money-rails'

group :development, :test do
  # Debug by calling 'byebug' anywhere in the code to stop
  # execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'yard'
end